/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MyComponent {
    /**
    * The first name
    */
    'data': any;
    'printConsoleLog': () => Promise<void>;
  }
  interface TagCloud {
    'fetchTags': () => Promise<void>;
  }
}

declare global {


  interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {}
  var HTMLMyComponentElement: {
    prototype: HTMLMyComponentElement;
    new (): HTMLMyComponentElement;
  };

  interface HTMLTagCloudElement extends Components.TagCloud, HTMLStencilElement {}
  var HTMLTagCloudElement: {
    prototype: HTMLTagCloudElement;
    new (): HTMLTagCloudElement;
  };
  interface HTMLElementTagNameMap {
    'my-component': HTMLMyComponentElement;
    'tag-cloud': HTMLTagCloudElement;
  }
}

declare namespace LocalJSX {
  interface MyComponent {
    /**
    * The first name
    */
    'data'?: any;
    'onMyCustomEvent'?: (event: CustomEvent<any>) => void;
  }
  interface TagCloud {
    'onMyCustomEvent'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'my-component': MyComponent;
    'tag-cloud': TagCloud;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'my-component': LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
      'tag-cloud': LocalJSX.TagCloud & JSXBase.HTMLAttributes<HTMLTagCloudElement>;
    }
  }
}


